name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - jupyter  # or 'notebook' for the Jupyter notebook server
